/*
Printing Long Strings
Occasionally,printf() statements are too long to put on one line.Because C ignores wthitespace(spaces,
tabs,newlines) except when used to separate elements,you can spread a statement over several lines,
as long as you put your line breaks between elements.For example.
    printf("The printf() function printed %d characters.\n",
         rv);
The line  is broken between the comma element and rv.And the example indents the rv.C ignores the 
extra spaces.
However,you cannot break a quoted string in the middle.Suppose you try something like the followinmg :
    printf("The printf() function printed %d
        characters.\n",rv);
C will complian that you have an illegal character in a string constant.You can use \n in a string 
to symbolize the newline character,but you can't have the actual newline character generated by the 
Enter (or Return)key in a string.
If you do have to split a string,you have three choices*/
#include<stdio.h>
int main(int argc, char const *argv[])
{
    printf("Here's one way to print a ");
    printf("long string.\n");
    printf("Here's another way to print a \
long string.\n");
    printf("Here's the newest way to print a "
        "long string.\n");          /*ANSI C*/
    return 0;
}
/*
Method 1 is to use more than one printf() statement.Because the first string printed doesn't end 
with a \n character,the second string continues where the first ends.
Method 2 is to termintate the end of the first line with a backslash/return combination.This causes 
the text onscreen to start a new line without a newline characrer being included in the string.The 
effect is to continue the string over to the next line.However,the next line has to start at the 
far left,as shown.If you indent that line,say,five spaces,those five spaces become part of the string.

Method 3,which ANSI C introduced,is string concatenation.If you follow one quoted string constant
with another,separated only by whitespace,C treats the combination as a single string,so the following 
three forms are equivalent:
    printf("Hello,young lovers,wherever you are.");
    printf("Hello,young"     "lovers" ",wherever you are.");
    printf("Hello,young lovers"
            ",wherever you are.");
With all these methods,you should include any required spaces in the strings:"young" "lovers"becomes
"younglvers",but the combination "young " "lovers" is "young lovers".

*/